/* eslint-disable no-shadow */

export const CTA_LIST = {
  VIEW_INVENTORY_NEW: 'VIEW_INVENTORY_NEW',
  VIEW_INVENTORY_USED: 'VIEW_INVENTORY_USED',
  VIEW_INVENTORY_NO_RESULTS: 'VIEW_INVENTORY_NO_RESULTS',
  BUILD_YOUR_AUDI: 'BUILD_YOUR_AUDI',
  ESTIMATE_YOUR_SAVINGS: 'ESTIMATE_YOUR_SAVINGS',
  CONTACT_DEALER: 'CONTACT_DEALER',
  CONTACT_DEALER_CARD: 'CONTACT_DEALER_CARD',
  WHY_BUY_CERTIFIED_PLUS: 'WHY_BUY_CERTIFIED_PLUS',
  CPO_FAQ: 'CPO_FAQ',
  CANCEL_FILTERS: 'CANCEL_FILTERS',
  APPLY_FILTERS: 'APPLY_FILTERS',
  LOAD_MORE: 'LOAD_MORE',
};

export const LEGAL_LIST = {
  APR: 'OFFER_APR',
  CASH: 'OFFER_CASH',
  PLUS: 'OFFER_PLUS',
  PRICE: 'OFFER_PRICE',
  RATE_RED: 'OFFER_RATE_REDUCTION',
};
