// eslint-disable-next-line no-shadow
enum ActionTypes {
  PROMOTIONS_FETCH_SUCCESS = 'PROMOTION_FETCH_SUCCESS',
  PROMOTIONS_FETCH_ERROR = 'PROMOTIONS_FETCH_ERROR',

  // Region filter actions
  REGION_FILTER_SET = 'REGION_FILTER_SET',
  REGION_FILTER_DELETE = 'REGION_FILTER_DELETE',

  // Vehicle type filter action
  VEHICLE_TYPE_FILTER_SET = 'VEHICLE_TYPE_FILTER_SET',
  VEHICLE_TYPE_FILTER_DELETE = 'VEHICLE_TYPE_FILTER_DELETE',

  // Body type filter action
  BODY_TYPE_SET = 'BODY_TYPE_SET',
  BODY_TYPE_DELETE = 'BODY_TYPE_DELETE',

  // Model family filter actions
  MODEL_FAMILY_SET = 'MODEL_FAMILY_SET',
  MODEL_FAMILY_DELETE = 'MODEL_FAMILY_DELETE',

  // Model year range actions
  MODEL_YEAR_RANGE_SET = 'MODEL_YEAR_RANGE_SET',
  MODEL_YEAR_RANGE_DELETE = 'MODEL_YEAR_RANGE_DELETE',

  CONFIRMED_FILTERS_SET = 'CONFIRMED_FILTERS_SET',
  TEMPORARY_FILTERS_SET = 'TEMPORARY_FILTERS_SET',
  ALL_FILTERS_CLEAR = 'ALL_FILTERS_CLEAR',
  FILTER_DELETE = 'FILTER_DELETE',
}

export default ActionTypes;
