service: some-feature-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  stage: api
  environment:
    NODE_TLS_REJECT_UNAUTHORIZED: '0'
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    DOMAIN_ENDPOINT_ENV_VAR: localhost
    STAGE: dev
plugins:
  - serverless-offline
functions:
  hello-world_get:
    handler: ../../dist/api/hello-world_get.handler
    events:
      - http:
          path: /hello-world
          method: get
          cors: true
  welcome_get_unprotected:
    handler: ../../dist/api/welcome_get_unprotected.handler
    events:
      - http:
          path: /welcome
          method: get
          cors: true
custom:
  serverless-offline:
    httpPort: 8000
useDotenv: true
