name: 'Dependabot Continuous integration'

on:
  pull_request:
    branches: [main]

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-dependabot:
    name: 'Dependabot Test Pull Request'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Load Cypress cache
        uses: actions/cache@v4.2.2
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress

      - name: Setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: |
          npm ci
          cd src/api && npm install

      - name: Check format
        run: npm run format:check

      - name: Check lint
        run: npm run lint:check

      - name: Check TypeScript
        run: npm run typescript:check

      - name: Unit test
        run: npm run test
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'

      - name: Build
        run: npm run build

      - name: Automated acceptance test
        uses: cypress-io/github-action@v6.7.16
        continue-on-error: true
        with:
          browser: chrome
          wait-on: 'http://localhost:3000'
          start: npm run serve:ssr:ci
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      - name: Test accessibility and performance
        run: npm run lighthouse:ci

      - name: Save lighthouse report
        uses: actions/upload-artifact@v4.6.1
        with:
          name: lighthouse-report
          path: .lighthouseci
          include-hidden-files: true
          if-no-files-found: error

  auto-merge:
    name: 'Automatically merge Dependabot upgrades'
    runs-on: ubuntu-latest
    needs: check-dependabot
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Automatically merge dependabot upgrades
        uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
          target: minor
