name: 'Notify Rocket.Chat channel on new Pull Request'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    name: 'Rocket.Chat notification'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Publish notification to Rocket.Channel
        if: env.ROCKET_CHAT_TOKEN != null && env.ROCKET_CHAT_USER_ID != null && env.ROCKET_CHAT_CHANNEL != null
        uses: oneaudi/oneaudi-rocket-chat-notification-action@v2.5.1
        env:
          ROCKET_CHAT_TOKEN: ${{ secrets.ROCKET_CHAT_TOKEN }}
          ROCKET_CHAT_USER_ID: ${{ secrets.ROCKET_CHAT_USER_ID }}
          ROCKET_CHAT_CHANNEL: ${{ secrets.ROCKET_CHAT_CHANNEL }}
        with:
          token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          user-id: ${{ secrets.ROCKET_CHAT_USER_ID }}
          channel: ${{secrets.ROCKET_CHAT_CHANNEL }}
