# Continuous integration / Validate App content for publishing Version into App Store
#
# Triggered by every push on a branch. This workflow verify if your appStore object in package.json
# is valid for publishing a new Version of your Feature App in the App Store.

name: 'Validate App content for publishing Version into App Store'

on: push

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  read-oneaudi-cli-json:
    name: 'Read oneaudi-cli.json'
    if: github.actor != 'dependabot[bot]'
    outputs:
      configs: ${{ steps.load-oneaudi-cli.outputs.configs }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - id: load-oneaudi-cli
        name: Load oneaudi-cli.json
        run: |
          content=`cat ./oneaudi-cli.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          echo "configs=$content" >> $GITHUB_OUTPUT

  validate-publishing-to-appstore:
    name: 'Validate App Store metadata'
    if: github.actor != 'dependabot[bot]' && fromJSON(needs.read-oneaudi-cli-json.outputs.configs).project.features.registeredInAppStore
    runs-on: ubuntu-latest
    needs: read-oneaudi-cli-json
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Setup node
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: |
          npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::374014568437:role/${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: valappstoresession
          aws-region: us-east-1

      - name: Validate app Content to publish in oneAudi App Store
        if: env.X_APPSTORE_ACCESS_KEY != null
        uses: oneaudi/oneaudi-publish-to-app-store-action@v5.1.0
        env:
          X_APPSTORE_ACCESS_KEY: ${{ secrets.X_APP_ACCESS_KEY }}
        with:
          BASE-URL: https://${{ github.event.repository.name }}.cdn.prod.${{ fromJSON(needs.read-oneaudi-cli-json.outputs.configs).project.awsDomain }}/${{ github.event.release.tag_name }}
          APP-VERSION: 0.0.0-${{ github.sha }}
          X-APPSTORE-ACCESS-KEY: ${{ secrets.X_APP_ACCESS_KEY }}
          DRY-RUN: true

      - name: Log skips reasons
        if: env.X_APPSTORE_ACCESS_KEY == null
        env:
          X_APPSTORE_ACCESS_KEY: ${{ secrets.X_APP_ACCESS_KEY }}
        run: echo "::warning::Some steps were skipped because some of your Github secrets are not set, please check X_APPSTORE_ACCESS_KEY"
